-- Run this once in Supabase's SQL editor (Project → SQL Editor → New query → paste → Run).
-- Creates the restaurants table, locks it down so anyone can read but only a
-- logged-in user (you) can write, and keeps updated_at current automatically.

create table if not exists restaurants (
  id bigint generated by default as identity primary key,
  borough text not null,
  hood text not null,
  name text not null,
  type text,
  stars smallint check (stars is null or (stars between 0 and 5)),
  cost text,
  mood text,
  rec text,
  dos text,
  donts text,
  rez text,
  misc text,
  top_pick boolean not null default false,
  description text,
  description_source text not null default 'generic',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table restaurants enable row level security;

drop policy if exists "public read" on restaurants;
create policy "public read" on restaurants
  for select
  using (true);

drop policy if exists "authenticated insert" on restaurants;
create policy "authenticated insert" on restaurants
  for insert
  to authenticated
  with check (true);

drop policy if exists "authenticated update" on restaurants;
create policy "authenticated update" on restaurants
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "authenticated delete" on restaurants;
create policy "authenticated delete" on restaurants
  for delete
  to authenticated
  using (true);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists restaurants_set_updated_at on restaurants;
create trigger restaurants_set_updated_at
  before update on restaurants
  for each row
  execute function set_updated_at();

create index if not exists restaurants_borough_hood_idx on restaurants (borough, hood);
